library(cgalMeshes)
library(rgl)
# parabola ####
x <- seq(-1, 1, length.out = 30)
parabola <- cylinder3d(cbind(x, x^2, 0), radius = 0.2, closed = -2)
mesh <- cgalMesh$new(parabola)$triangulate()
mesh$smoothShape(time = 0.0005, iterations = 10)
sparabola <- mesh$getMesh()
open3d(windowRect = 50 + c(0, 0, 900, 450))
mfrow3d(1, 2)
view3d(0, 0, zoom = 0.9)
shade3d(parabola, color = "orange")
wire3d(parabola)
next3d()
view3d(0, 0)
shade3d(sparabola, color = "green")
wire3d(sparabola)
