library(cgalMeshes)
library(rgl)
mesh <- PoissonReconstruction(SolidMobiusStrip)
mesh$computeNormals()
rmesh <- mesh$getMesh()
open3d(windowRect = 50 + c(0, 0, 512, 512))
view3d(20, -40, zoom = 0.85)
shade3d(rmesh, color = "darkorange")
wire3d(rmesh)

