# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AFSreconstruction_cpp <- function(pts) {
    .Call(`_cgalMeshes_AFSreconstruction_cpp`, pts)
}

mandelbulb <- function(angle_bound, radius_bound, distance_bound) {
    .Call(`_cgalMeshes_mandelbulb`, angle_bound, radius_bound, distance_bound)
}

spikes <- function(angle_bound, radius_bound, distance_bound) {
    .Call(`_cgalMeshes_spikes`, angle_bound, radius_bound, distance_bound)
}

brain <- function(filename, isovalue, center, radius, angle_bound, radius_bound, distance_bound) {
    .Call(`_cgalMeshes_brain`, filename, isovalue, center, radius, angle_bound, radius_bound, distance_bound)
}

polynomial <- function(powers, coeffs, x, y, z) {
    invisible(.Call(`_cgalMeshes_polynomial`, powers, coeffs, x, y, z))
}

