# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AFSreconstruction_cpp <- function(pts) {
    .Call(`_cgalMeshes_AFSreconstruction_cpp`, pts)
}

cxhull <- function(pts) {
    .Call(`_cgalMeshes_cxhull`, pts)
}

cxhullsIntersection <- function(Pts, origin_) {
    .Call(`_cgalMeshes_cxhullsIntersection`, Pts, origin_)
}

gTriangle <- function(A, B, C, s, iterations) {
    .Call(`_cgalMeshes_gTriangle`, A, B, C, s, iterations)
}

AlgebraicMesh <- function(powers, coeffs, isolevel, sphereCenter, sphereRadius, angle_bound, radius_bound, distance_bound, error_bound) {
    .Call(`_cgalMeshes_AlgebraicMesh`, powers, coeffs, isolevel, sphereCenter, sphereRadius, angle_bound, radius_bound, distance_bound, error_bound)
}

VoxelToMesh <- function(filename, isovalue, center, radius, angle_bound, radius_bound, distance_bound, error_bound) {
    .Call(`_cgalMeshes_VoxelToMesh`, filename, isovalue, center, radius, angle_bound, radius_bound, distance_bound, error_bound)
}

meshTopology <- function(nu, nv) {
    .Call(`_cgalMeshes_meshTopology`, nu, nv)
}

sTriangle <- function(A, B, C, center, radius, iterations) {
    .Call(`_cgalMeshes_sTriangle`, A, B, C, center, radius, iterations)
}

