# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AFSreconstruction_cpp <- function(pts, nneighs) {
    .Call(`_cgalMeshes_AFSreconstruction_cpp`, pts, nneighs)
}

SSSreconstruction_cpp <- function(pts, scaleIterations, nneighs, nsamples, separateShells, forceManifold, borderAngle) {
    .Call(`_cgalMeshes_SSSreconstruction_cpp`, pts, scaleIterations, nneighs, nsamples, separateShells, forceManifold, borderAngle)
}

gTriangle <- function(A, B, C, s, iterations) {
    .Call(`_cgalMeshes_gTriangle`, A, B, C, s, iterations)
}

meshTopology <- function(nu, nv, uperiodic, vperiodic) {
    .Call(`_cgalMeshes_meshTopology`, nu, nv, uperiodic, vperiodic)
}

sTriangle <- function(A, B, C, center, radius, iterations) {
    .Call(`_cgalMeshes_sTriangle`, A, B, C, center, radius, iterations)
}

